//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//  Template generated by Sally'sZone
//

import UIKit
import RxSwift
import RxCocoa
import RxOptional
class VFUK___VARIABLE_productName:identifier___ViewController: VFUKBaseViewController {

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        self.viewModel =  VFUK___VARIABLE_productName:identifier___ViewModel()
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
        configureBinding()

    }
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        /// tracking screen
        VFUKGlobalTrackingHelper.sharedTrackingHelper.trackScreen(screen: VFUKTrackingConstants.vfuk___VARIABLE_productName:identifier___ScreenName)
    }

    /// setup function for calling all needed observables for display and draw view
    fileprivate func setup() {

    }
    /// Handles the binding to the viewModel and applies the necessary data transformations
    fileprivate func configureBinding() {

    }

    /// in retry func we just need to call setup func
    override func retryAction() {
        self.setup()
    }


}
