//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//  Template generated by Sally'sZone
//
import UIKit
import RxSwift
import RxCocoa
import RxOptional

class VFUK___VARIABLE_productName:identifier___CachingPolicy: VFUKCachingPolicy, VFUKCachingPolicyProtocol {

	override init() {
		super.init()
		self.maxAge =
		self.pollInterval =

	}
	func isMemoryCacheValid(_ lastApiCall: TimeInterval?) -> Bool {
		return false
	}

	func isDiskCacheValid(_ lastApiCall: TimeInterval?) -> Bool {
		return false
	}

	func isKeychainCacheValid() -> Bool {
		return false
	}

	func shouldCallApi(_ lastApiCall: TimeInterval?) -> Bool {
		return true
	}
	func shouldUseCache() -> Bool {
		return true
	}

	func shouldUseMemoryCache() -> Bool {
		return false
	}

	func shouldUseDiskCache() -> Bool {
		return true
	}

	func shouldUseKeychainCache() -> Bool {
		return false
	}

}
