//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//  Template generated by Sally'sZone
//
import UIKit
import RxSwift
import RxCocoa
import RxOptional

class VFUK___VARIABLE_productName:identifier___ViewModel: VFUKBaseViewModel {
    private let interactor: VFUK___VARIABLE_productName:identifier___Interactor

    override init() {
        interactor = VFUK___VARIABLE_productName:identifier___Interactor()
        super.init()
        configureBinding()
    }
    /// Handles the binding to the interactor and applies the necessary data transformations
    private func configureBinding() {

    }
}
