//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//  Template generated by Sally'sZone
//

import UIKit
import RxSwift
import RxCocoa
import RxOptional
class VFUK___VARIABLE_productName:identifier___Dispatcher: VFUKBaseDispatcher {

}
